import Footer from '@/components/shared/footer'
import Header from '@/components/shared/header'
import ScrollToTop from '@/components/shared/scrolltotop'
import { APP_DESCRIPTION, APP_NAME } from '@/lib/constants'
import { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
  title: `${APP_NAME} - ${APP_DESCRIPTION}`,
  description: 'Generated by create next app',
}

export default function ContentLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <Header />
      <main className="flex-1 wrapper">{children}</main>
      <ScrollToTop />
      <Footer />
    </div>
  )
}
